package com.dnd.ui;

public enum SceneType {
    LOGIN,
    REGISTER,
    VERIFY_EMAIL,
    FORGOT_PASSWORD,
    RESET_PASSWORD,
    LANDING,
    CAMPAIGN_SELECTION,
    CREATE_CAMPAIGN,
    DM_MENU,
    DM_ONLINE_SESSION,
    PLAYER_CHARACTER_SELECTION,
    PLAYER_HOME,
    PLAYER_ONLINE_SESSION,
    ENTITY_LIST,
    ENTITY_DETAIL,
    MAP_VIEW,
    MAP_EDITOR,
    CHARACTER_PROFILE,
    STORYLINE
}
